GET http://127.0.0.1:8000/

###

POST http://127.0.0.1:8000/temperature
Content-Type: application/json

{
    "location": "MoScow",
    "temperature": -14.9
}

###

GET http://127.0.0.1:8000/temperature/locations

###

GET http://127.0.0.1:8000/temperature/munich
