GET http://127.0.0.1:8000/get-data

###

POST http://127.0.0.1:8000/post-data
Content-Type: application/json

{
    "name": "Sofya"
}

###

POST http://127.0.0.1:8000/temperature
Content-Type: application/json

{
    "location": "London",
    "temperature": 14.9
}

###

GET http://127.0.0.1:8000/temperature/locations